local combat = Combat()
combat:setParameter(COMBAT_PARAM_EFFECT, CONST_ME_MAGIC_BLUE)
combat:setParameter(COMBAT_PARAM_DISPEL, CONDITION_FIRE CONDITION_ENERGY CONDITION_CURSED CONDITION_POISON)
combat:setParameter(COMBAT_PARAM_AGGRESSIVE, false)

local spell = Spell("instant")

function spell.onCastSpell(creature, variant)
	return combat:execute(creature, variant)
end

spell:name("Ultimate Cure")
spell:words("exana ultimate")
spell:group("healing")
spell:vocation("sorcerer;true", "master sorcerer;true","druid;true", "elder druid;true", "paladin;true", "royal paladin;true", "knight;true", "elite knight;true")
spell:castSound(SOUND_EFFECT_TYPE_SPELL_CURE_BURNING)
spell:id(600)
spell:cooldown(6000)
spell:groupCooldown(1000)
spell:level(250)
spell:mana(300)
spell:isSelfTarget(true)
spell:isAggressive(false)
spell:isPremium(true)
spell:needLearn(false)
spell:register()